uint8 mode # What drone mode is to be requested
uint8 MODE_UNASSIGNED = 0

uint8 MODE_TAKEOFF_START = 1
uint8 MODE_TAKEOFF_END = 2

uint8 MODE_MISSION_START = 3
uint8 MODE_MISSION_END = 4

uint8 MODE_LAND_START = 5
uint8 MODE_LAND_END = 6

uint8 MODE_RTL_START = 7
uint8 MODE_RTL_END = 8

uint8 MODE_HOLD = 9
uint8 MODE_KILL = 10
---
bool success